# Generated by Django 5.0.1 on 2025-05-03 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_student_is_ta_professor_subject_student_ta_subjects"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="number_of_questions",
        ),
    ]
