# Generated by Django 5.0.1 on 2025-05-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0004_comment_parent_exercise_number_of_questions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="deadline",
            field=models.DateField(blank=True, null=True),
        ),
    ]
