# Generated by Django 5.0.1 on 2025-05-08 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0002_course_end_date_course_start_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="course",
            name="start_date",
        ),
    ]
