# Generated by Django 5.0.1 on 2025-05-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0003_remove_course_end_date_remove_course_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="end_date",
            field=models.DateField(
                blank=True, help_text="Date when this course ends", null=True
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="start_date",
            field=models.DateField(
                blank=True, help_text="Date when this course begins", null=True
            ),
        ),
    ]
