# Generated by Django 5.0.1 on 2025-05-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0004_course_end_date_course_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="end_date",
            field=models.DateField(help_text="Date when this course ends"),
        ),
        migrations.AlterField(
            model_name="course",
            name="start_date",
            field=models.DateField(help_text="Date when this course begins"),
        ),
    ]
